#!/usr/bin/env python3
"""
scripts/target_alerts.py — Flag watchlist names that hit the research buy_target.

NOTE: buy_target values are generated by the research pipeline (LLM/manual
analysis), NOT set by the user. They are suggested entry levels, not personal
conviction targets. This checks live prices and surfaces any name now trading
at or below its research target so you can review it.

Output:
  data/target_alerts.json  (read by build_dashboard.py)

Usage:
    python3 scripts/target_alerts.py
"""

import json
import os
import sys
from datetime import datetime, timezone

SCRIPT_DIR     = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WATCHLIST_PATH = os.path.join(SCRIPT_DIR, "data", "watchlist.json")
QUOTES_PATH    = os.path.join(SCRIPT_DIR, "data", "quotes_cache.json")
OUTPUT_PATH    = os.path.join(SCRIPT_DIR, "data", "target_alerts.json")

TOLERANCE = 0.03   # within 3% of target counts as "hit"


def _load(path, default=None):
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return default if default is not None else {}


def _refresh_live_targets(wl: dict, quotes: dict) -> bool:
    """Recompute buy_target from buy_trigger_drawdown_pct + the CURRENT 52-week
    high. research_ticker.py stores the drawdown trigger (a durable judgment,
    e.g. "-20%") rather than a dollar figure; this makes the displayed target
    self-heal every quote refresh instead of rotting as a stale fixed price.
    Candidates researched before this existed have no trigger and are untouched.
    """
    changed = False
    for c in wl.get("candidates", []):
        pct = c.get("buy_trigger_drawdown_pct")
        if pct is None:
            continue
        q = quotes.get(c.get("ticker", ""), {})
        high, price = q.get("high_52w"), q.get("price")

        if pct == 0:
            # 0 means "no pullback required — current levels already clear the
            # bar". Applying the drawdown formula here would set the target to
            # the 52-week HIGH, making a buy-ready name render as a huge fake
            # discount (e.g. "54% below target"). Anchor to the live price so
            # the gap reads ~0% and the name shows as at-target, not on sale.
            if not price:
                continue
            new_target = round(price, 2)
            c["no_pullback_gate"] = True
        else:
            if not high:
                continue
            new_target = round(high * (1 + pct / 100), 2)
            c["no_pullback_gate"] = False

        if c.get("buy_target") != new_target:
            c["buy_target"] = new_target
            changed = True
    return changed


def main():
    wl     = _load(WATCHLIST_PATH, {"candidates": []})
    quotes = _load(QUOTES_PATH).get("tickers", {})

    if _refresh_live_targets(wl, quotes):
        with open(WATCHLIST_PATH, "w") as f:
            json.dump(wl, f, indent=2)
        print("🔄 Refreshed live buy targets from current 52-week highs.")

    hits = []
    approaching = []
    for c in wl.get("candidates", []):
        ticker = c.get("ticker", "")
        target = c.get("buy_target")
        verdict = c.get("verdict", "")
        if not target or verdict in ("PASS", "RED FLAG"):
            continue
        q = quotes.get(ticker, {})
        price = q.get("price")
        if not price:
            continue

        gap_pct = round((price - target) / target * 100, 1)
        rec = {
            "ticker":     ticker,
            "name":       c.get("name", ticker),
            "verdict":    verdict,
            "confidence": c.get("confidence"),
            "theme":      c.get("theme"),
            "price":      price,
            "buy_target": target,
            "gap_pct":    gap_pct,
            "next_action": c.get("next_action", ""),
        }
        if price <= target * (1 + TOLERANCE):
            hits.append(rec)
        elif price <= target * 1.10:   # within 10% above target
            approaching.append(rec)

    hits.sort(key=lambda x: x["gap_pct"])
    approaching.sort(key=lambda x: x["gap_pct"])

    out = {
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "hits":         hits,
        "approaching":  approaching,
    }
    with open(OUTPUT_PATH, "w") as f:
        json.dump(out, f, indent=2)

    if hits:
        print(f"🎯 {len(hits)} name(s) AT or BELOW buy target:")
        for h in hits:
            print(f"  {h['ticker']} ${h['price']} (target ${h['buy_target']}, {h['gap_pct']:+.1f}%) [{h['verdict']}]")
    else:
        print("No names at buy target right now.")
    if approaching:
        print(f"\n👀 {len(approaching)} approaching (within 10%): {', '.join(a['ticker'] for a in approaching)}")
    print(f"\n✅ Target alerts → {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
